version: '3.7'
services:
  server:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODEL_URL=file:///app/model/model.json
    command: node ./src/server.js
    volumes:
      - ./src:/app/src

